eval_datasets = []
epochs = 100
micro_batch_size_per_gpu = 2
gradient_accumulation_steps = 4
pipeline_stages = 1
warmup_steps = 100
blocks_to_swap = 20
activation_checkpointing = true
save_dtype = 'bfloat16'
caching_batch_size = 1
partition_method = 'parameters'
output_dir = 'E:/comfyuiMQ/ComfyUI_windows_portable/ComfyUI/output/123'
disable_block_swap_for_eval = false
gradient_clipping = 1.0
save_every_n_epochs = 1
checkpoint_every_n_minutes = 120
dataset = 'E:/comfyuiMQ/ComfyUI_windows_portable/ComfyUI/custom_nodes/Diffusion_pipe_in_ComfyUI_Win/dataset/dataset.toml'
lr_scheduler = 'linear'
map_num_proc = 1

[optimizer]
type = 'AdamW8bitKahan'
lr = 9e-5
betas = [ 0.9, 0.99,]
weight_decay = 0.01

[model]
type = 'qwen2511'
diffusers_path = 'E:/comfyuiMQ/ComfyUI_windows_portable/ComfyUI/custom_nodes/Diffusion_pipe_in_ComfyUI_Win/Qwen-Image-Edit-2511'
dtype = 'bfloat16'
timestep_sample_method = 'logit_normal'
transformer_dtype = 'bfloat16'

[adapter]
type = 'lora'
rank = 32
dtype = 'bfloat16'
