eval_datasets = [{name = 'validation_set', config = 'E:/comfyuiMQ/ComfyUI_windows_portable/ComfyUI/custom_nodes/Diffusion_pipe_in_ComfyUI_Win/dataset/evaldataset.toml'}]
epochs = 192
micro_batch_size_per_gpu = 1
gradient_accumulation_steps = 4
pipeline_stages = 1
warmup_steps = 100
blocks_to_swap = 40
activation_checkpointing = true
save_dtype = 'bfloat16'
caching_batch_size = 1
partition_method = 'parameters'
output_dir = 'E:/comfyuiMQ/ComfyUI_windows_portable/ComfyUI/output/123'
disable_block_swap_for_eval = false
gradient_clipping = 1.0
eval_every_n_epochs = 16
eval_before_first_step = true
eval_micro_batch_size_per_gpu = 1
eval_gradient_accumulation_steps = 1
save_every_n_epochs = 1
checkpoint_every_n_minutes = 120
dataset = 'E:/comfyuiMQ/ComfyUI_windows_portable/ComfyUI/custom_nodes/Diffusion_pipe_in_ComfyUI_Win/dataset/dataset.toml'
lr_scheduler = 'linear'

[optimizer]
type = 'AdamW8bitKahan'
lr = 9e-5
betas = [ 0.9, 0.99,]
weight_decay = 0.01

[model]
type = 'aura_flow'
aura_flow_path = 'E:/comfyuiMQ/ComfyUI_windows_portable/ComfyUI/models/diffusers/Qwen-Image'
text_encoder_path = ''
vae_path = ''
max_sequence_length = 768
dtype = 'bfloat16'
timestep_sample_method = 'logit_normal'
transformer_dtype = 'float8'

[adapter]
type = 'lora'
rank = 16
dtype = 'bfloat16'
