epochs = 190
micro_batch_size_per_gpu = 1
gradient_accumulation_steps = 1
pipeline_stages = 1
warmup_steps = 0
blocks_to_swap = 0
activation_checkpointing = true
save_dtype = 'bfloat16'
caching_batch_size = 1
partition_method = 'parameters'
output_dir = 'E:/comfyuiMQ/ComfyUI_windows_portable/ComfyUI/output/123'
disable_block_swap_for_eval = true
gradient_clipping = 1.0
eval_datasets = []
save_every_n_epochs = 1
checkpoint_every_n_minutes = 120
dataset = 'E:/comfyuiMQ/ComfyUI_windows_portable/ComfyUI/custom_nodes/Diffusion_pipe_in_ComfyUI_Win/dataset/dataset.toml'
checkpoint_every_n_epochs = 1

[optimizer]
type = 'AdamW8bitKahan'
lr = 2e-5
betas = [ 0.9, 0.99,]
weight_decay = 0.01
gradient_release = false

[model]
type = 'qwen_image'
diffusers_path = 'E:/comfyuiMQ/ComfyUI_windows_portable/ComfyUI/models/diffusers/Qwen-Image'
transformer_path = 'E:/comfyuiMQ/ComfyUI_windows_portable/ComfyUI/models/diffusion_models/qwen_edit/qwen_image_edit_bf16.safetensors'
dtype = 'bfloat16'
timestep_sample_method = 'logit_normal'
transformer_dtype = 'float8'

[adapter]
type = 'lora'
rank = 16
dtype = 'bfloat16'
